/*
 * generated by Xtext
 */
package edu.uci.ics.asterixdb.ui.contentassist

import edu.uci.ics.asterixdb.ui.contentassist.AbstractAQLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AQLProposalProvider extends AbstractAQLProposalProvider {
}
