/*
 * generated by Xtext
 */
package edu.uci.ics.asterixdb;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AQLRuntimeModule extends edu.uci.ics.asterixdb.AbstractAQLRuntimeModule {

}
