/*
* generated by Xtext
*/
package edu.uci.ics.asterixdb;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AQLStandaloneSetup extends AQLStandaloneSetupGenerated{

	public static void doSetup() {
		new AQLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

