/*
 * generated by Xtext
 */
package edu.uci.ics.asterixdb.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AQLUiModule extends edu.uci.ics.asterixdb.ui.AbstractAQLUiModule {
	public AQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
